services:
    airflow_db:
        image: postgres:15
        container_name: airflow_db
        restart: always
        environment:
            POSTGRES_USER: airflow
            POSTGRES_PASSWORD: airflow
            POSTGRES_DB: airflow
        ports:
            - "5435:5432"
        networks:
            - airflow_net

    postgres1:
        image: postgres:15
        container_name: postgres1
        restart: always
        environment:
            POSTGRES_USER: user1
            POSTGRES_PASSWORD: pass1
            POSTGRES_DB: db1
        ports:
            - "5433:5432"
        networks:
            - airflow_net

    postgres2:
        image: postgres:15
        container_name: postgres2
        restart: always
        environment:
            POSTGRES_USER: user2
            POSTGRES_PASSWORD: pass2
            POSTGRES_DB: db2
        ports:
            - "5434:5432"
        networks:
            - airflow_net

    airflow:
        build: .
        container_name: airflow
        restart: always
        depends_on:
            - airflow_db
            - postgres1
            - postgres2
        environment:
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@airflow_db:5432/airflow
            - PYTHONPATH=/opt/airflow/.local:/opt/airflow/.local/lib/python3.12/site-packages:$PYTHONPATH
        volumes:
            - ./dags:/opt/airflow/dags
            - ./plugins:/opt/airflow/plugins
        ports:
            - "8080:8080"
        networks:
            - airflow_net
        entrypoint: >
            /bin/bash -c "
            echo 'Starting Airflow setup...' &&

            echo 'Waiting for the database to be ready...' &&
            while ! pg_isready -h airflow_db -p 5432 -U airflow; do
                echo 'Database not ready, waiting...';
                sleep 5;
            done;

            echo 'Database ready! Running Airflow migrations...' &&
            airflow db init &&
            airflow db upgrade &&

            if ! airflow users list | grep -q 'admin'; then
                echo 'Creating default user...' &&
                airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com
            else
                echo 'Admin user already exists, skipping creation.'
            fi

            echo 'Starting Airflow services...' &&
            airflow scheduler & airflow webserver"

networks:
    airflow_net:
        driver: bridge
